version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - redis
    networks:
      - bitebase_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bitebase_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  bitebase_network:
    driver: bridge

volumes:
  redis_data: 